// <auto-generated />
using System;
using ControlTalleresMVP.Persistence.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlTalleresMVP.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20250902051407_configuraciones")]
    partial class configuraciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_alumno");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int?>("PromotorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_promotor");

                    b.Property<int?>("SedeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sede");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("AlumnoId");

                    b.HasIndex("PromotorId");

                    b.HasIndex("SedeId");

                    b.HasIndex(new[] { "Nombre" }, "idx_alumnos_nombre");

                    b.ToTable("alumnos", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Configuracion", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("TEXT")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Clave");

                    b.ToTable("configuraciones", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Generacion", b =>
                {
                    b.Property<int>("GeneracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_generacion");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("GeneracionId");

                    b.ToTable("generaciones", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_inscripcion");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_alumno");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT")
                        .HasColumnName("costo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<int>("GeneracionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_generacion");

                    b.Property<int>("TallerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_taller");

                    b.HasKey("InscripcionId");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("GeneracionId");

                    b.HasIndex("TallerId");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Promotor", b =>
                {
                    b.Property<int>("PromotorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_promotor");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("PromotorId");

                    b.ToTable("promotores", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sede");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("SedeId");

                    b.ToTable("sedes", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Taller", b =>
                {
                    b.Property<int>("TallerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_taller");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("horario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("TallerId");

                    b.ToTable("talleres", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Promotor", "Promotor")
                        .WithMany("Alumnos")
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Sede", "Sede")
                        .WithMany("Alumnos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Promotor");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Inscripcion", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Generacion", "Generacion")
                        .WithMany("Inscripciones")
                        .HasForeignKey("GeneracionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Taller", "Taller")
                        .WithMany("Inscripciones")
                        .HasForeignKey("TallerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Generacion");

                    b.Navigation("Taller");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Generacion", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Promotor", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Sede", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Taller", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
