// <auto-generated />
using System;
using ControlTalleresMVP.Persistence.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlTalleresMVP.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20250831204213_sedes")]
    partial class sedes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_alumno");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int?>("PromotorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_promotor");

                    b.Property<int?>("SedeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sede");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("AlumnoId");

                    b.HasIndex("PromotorId");

                    b.HasIndex("SedeId");

                    b.HasIndex(new[] { "Nombre" }, "idx_alumnos_nombre");

                    b.ToTable("alumnos", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Promotor", b =>
                {
                    b.Property<int>("PromotorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_promotor");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("PromotorId");

                    b.ToTable("promotores", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sede");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("SedeId");

                    b.ToTable("sedes", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Promotor", "Promotor")
                        .WithMany("Alumnos")
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Sede", "Sede")
                        .WithMany("Alumnos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Promotor");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Promotor", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Sede", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
