// <auto-generated />
using System;
using ControlTalleresMVP.Persistence.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlTalleresMVP.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20250830021822_promotoresSedes")]
    partial class promotoresSedes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_alumno");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<int>("IdPromotor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_promotor");

                    b.Property<int>("IdSede")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sede");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("IdAlumno");

                    b.HasIndex("IdPromotor");

                    b.HasIndex("IdSede");

                    b.HasIndex(new[] { "Nombre" }, "idx_alumnos_nombre");

                    b.ToTable("alumnos", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Promotor", b =>
                {
                    b.Property<int>("IdPromotor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_promotor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("IdPromotor");

                    b.ToTable("promotores", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sede");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("IdSede");

                    b.ToTable("sedes", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Promotor", "Promotor")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdPromotor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Sede", "Sede")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Promotor");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Promotor", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Sede", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
