// <auto-generated />
using System;
using ControlTalleresMVP.Persistence.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlTalleresMVP.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20250904141535_InscripcionesUniqueCanceladoEn")]
    partial class InscripcionesUniqueCanceladoEn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.Property<int>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_alumno");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int?>("PromotorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_promotor");

                    b.Property<int?>("SedeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sede");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("AlumnoId");

                    b.HasIndex("Nombre");

                    b.HasIndex("PromotorId");

                    b.HasIndex("SedeId");

                    b.ToTable("alumnos", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cargo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alumno_id");

                    b.Property<int?>("ClaseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("clase_id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<int?>("InscripcionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inscripcion_id");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("monto");

                    b.Property<decimal>("SaldoActual")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("saldo_actual");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.HasKey("CargoId");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("InscripcionId");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Configuracion", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("TEXT")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Clave");

                    b.ToTable("configuraciones", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Generacion", b =>
                {
                    b.Property<int>("GeneracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_generacion");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("GeneracionId");

                    b.ToTable("generaciones", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_inscripcion");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alumno_id");

                    b.Property<DateTime?>("CanceladaEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancelada_en");

                    b.Property<decimal>("Costo")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("costo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<int>("GeneracionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generacion_id");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<decimal>("SaldoActual")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("saldo_actual");

                    b.Property<int>("TallerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("taller_id");

                    b.HasKey("InscripcionId");

                    b.HasIndex("GeneracionId");

                    b.HasIndex("TallerId");

                    b.HasIndex("AlumnoId", "TallerId", "GeneracionId", "Eliminado", "CanceladaEn")
                        .IsUnique();

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pago");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alumno_id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("metodo");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("monto_total");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT")
                        .HasColumnName("notas");

                    b.Property<string>("Referencia")
                        .HasColumnType("TEXT")
                        .HasColumnName("referencia");

                    b.HasKey("PagoId");

                    b.HasIndex("AlumnoId");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.PagoAplicacion", b =>
                {
                    b.Property<int>("PagoAplicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_pago_aplicacion");

                    b.Property<int>("CargoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cargo_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<decimal>("MontoAplicado")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("monto_aplicado");

                    b.Property<int>("PagoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pago_id");

                    b.HasKey("PagoAplicacionId");

                    b.HasIndex("CargoId");

                    b.HasIndex("PagoId");

                    b.ToTable("pago_aplicaciones", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Promotor", b =>
                {
                    b.Property<int>("PromotorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_promotor");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("PromotorId");

                    b.ToTable("promotores", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sede");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("SedeId");

                    b.ToTable("sedes", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Taller", b =>
                {
                    b.Property<int>("TallerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_taller");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("eliminado_en");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("horario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("TallerId");

                    b.ToTable("talleres", (string)null);
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Promotor", "Promotor")
                        .WithMany("Alumnos")
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Sede", "Sede")
                        .WithMany("Alumnos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Promotor");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Cargo", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Alumno", "Alumno")
                        .WithMany("Cargos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Inscripcion", "Inscripcion")
                        .WithMany("Cargos")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Alumno");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Inscripcion", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Generacion", "Generacion")
                        .WithMany("Inscripciones")
                        .HasForeignKey("GeneracionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Taller", "Taller")
                        .WithMany("Inscripciones")
                        .HasForeignKey("TallerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Generacion");

                    b.Navigation("Taller");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Pago", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Alumno", "Alumno")
                        .WithMany("Pagos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.PagoAplicacion", b =>
                {
                    b.HasOne("ControlTalleresMVP.Persistence.Models.Cargo", "Cargo")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlTalleresMVP.Persistence.Models.Pago", "Pago")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Alumno", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Inscripciones");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Cargo", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Generacion", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Inscripcion", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Pago", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Promotor", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Sede", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("ControlTalleresMVP.Persistence.Models.Taller", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
